# git_python_practise_rep
Try to clone the repo in your local system . Solve the questions given in the practise file and then push the file into the repo back.
